sudo: false
language: perl
perl:
  - "blead"
  - "dev"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
matrix:
  allow_failures:
    - perl: "blead"
    - perl: "dev"
env:
  global:
    - COVERAGE="coveralls codecov"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpanm -f Net::SSLeay
